### ISSUE TITLE
Bitmask inside binary section of RsaSha256 and ThresholdSha256

### ISSUE THREAD

**Issue by jtremback** [interledger/five-bells-condition#10]
In RSA-SHA256, and in Threshold-SHA256, there is `VARUINT BITMASK = 2`. Isn't the bitmask going in the string envelope format? I would be in support of removing this from the binary payload.

**Comment by justmoon** [comment]
Good point. I've removed it from RSA-SHA-256 with this commit: https://github.com/interledger/five-bells-condition/commit/259f720f79a5b23afd027aa9f6e48a7002f89fd6#diff-6e196c98aaadaa54d9ba9bbe92a13320L187

For THRESHOLD-SHA-256 I think we should keep it, see [this comment](https://github.com/interledger/five-bells-condition/issues/6#issuecomment-195350420).
