### ISSUE TITLE
When multiple meta-type bits are set, which meta-type is it?

### ISSUE THREAD

**Issue by justmoon** [interledger/five-bells-condition#5]
The bitmask works by setting bits based on the type of the meta-condition and the types of subconditions.

However, what happens when a subcondition is also a meta-condition of a different type?

For example, if 0x04 is the threshold SHA256 condition type, 0x40 is the threshold SHA512 condition type and 0x01 is the SHA256 hashlock type, what type of condition is 0x45? Is it a SHA512 threshold condition with SHA256 threshold and hashlock types in it? Or is it a SHA256 threshold condition with SHA256 hashlock and SHA512 threshold subconditions in it.

Proposed solution:

Give each condition type a unique ID which also matches the position of its bit in the bitmask. So condition 1 is 0x01, 2 is 0x02, 3 is 0x04 and so on. Use the version field to denote the condition type. Only meta types provide a bitmask. The condition type field can double as a version field since the following data depends on the condition type and implementations will reject types they do not recognize.

Examples:

```
// Types:
// 1 ... 0x01 ... SHA256 hashlock
// 2 ... 0x02 ... RSA-SHA256
// 3 ... 0x04 ... SHA256 threshold
// 7 ... 0x40 ... SHA512 threshold

Simple SHA256 hashlock
cc:1:47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU:1
// 1 ... version 1 = SHA256 hashlock

SHA256 threshold containing SHA256 hashlock
cc:3:5:UNhY4JhezH9gQYqvDMWrWH9CwlcKiECVqejMrND2VFw:50
// 3 ... version 3 = SHA256 threshold
// 5 ... bitmask 0x05 =
//    0x01 SHA256 hashlock
//    0x04 SHA256 threshold

SHA512 threshold containing SHA256 threshold and hashlock
cc:7:5:X7FnnghnQFm3LicdiQLBGhJ7tTAbBV3Hf6A5Mq2lalY:50
// 7 ... version 7 = SHA512 threshold
// 5 ... bitmask 0x05 =
//    0x01 SHA256 hashlock
//    0x04 SHA256 threshold

SHA256 threshold containing SHA512 threshold and SHA256 hashlock
cc:3:41:yuumEiY8oD40Uo5_FCkzYj_ELArGV5C6CeGk43qtFcE:50
// 3 ... version 3 = SHA256 threshold
// 41 ... bitmask 0x41 =
//    0x01 SHA256 hashlock
//    0x40 SHA512 threshold
```

**Comment by emschwartz** [comment]
Why do you need to differentiate between conditions and meta-conditions?

My understanding is that the point of the bitmask to allow different systems to efficiently check whether they can support a given condition. If so, it seems like the most straightforward solution would be having one bit per algorithm (or meta-algorithm) that is set to `1` if the algorithm is used and `0` if not. It wouldn't matter whether a condition is a meta-condition or not, just whether that algorithm is used at all.

What am I missing?

It sounds like the problem with this would be that having 1 bit per algorithm added could get quite large over time, which wouldn't be ideal. If that's the issue, though, I don't exactly see how this solution addresses it.

**Comment by jtremback** [comment]
It sounds like the root of this issue is the fact that you are using the bitmask to both check whether an implementation can handle a condition, and which threshold condition to parse it with. In that case, if I understand your solution correctly, you are separating them so that the overall compatibility check happens separately from figuring out which code to use to parse the threshold condition.

If that's the case, it seems good.

**Comment by adrianhopebailie** [comment]
> you are separating them so that the overall compatibility check happens separately from figuring out which code to use to parse the threshold condition.

I don't follow this. Are you saying the version number is all that's used to decide if an implementation supports the condition types being used?

How does the proposed solution solve the question of which threshold condition to use for parsing?

**Comment by justmoon** [comment]
Talking to @emschwartz I realized that you never need to parse conditions. That means not only do we not need this feature, but I can remove the Condition class and all subclasses from my implementation.

You generate conditions, you serialize them, you store them as strings. You compare those strings against the strings you get from validating fulfillments. You never parse conditions. Which means you don't actually need to know what type of condition it is. You need the bitmask and the max_fulfillment_length to know if the host is going to be able to process the fulfillment, but that's it. Other than that you never need to parse the condition.

**Comment by jtremback** [comment]
Nice
