### ISSUE TITLE
Max dynamic message length vs max fulfillment length

### ISSUE THREAD

**Issue by jtremback** [interledger/five-bells-condition#9]
Don't these two fields duplicate data?

**Comment by jtremback** [comment]
@justmoon

**Comment by justmoon** [comment]
One is in the condition, one is in the fulfillment. The one in the fulfillment is necessary to generate the one in the condition. The one in the condition is necessary to know whether the server is going to support the fulfillment (before you see the actual fulfillment.) Does that answer your question?

**Comment by jtremback** [comment]
The one in the fulfillment must be the max dynamic message (suffix) length, right? Also, it looks like it's in both.

Also, can't you just generate the max fulfillment length from the fulfillment itself?

**Comment by jtremback** [comment]
Don't you already have the length of the dynamic message if you are making a fulfillment?

**Comment by jtremback** [comment]
After some thought, I agree that it's best to use the dynamic message length because it keeps the format of the fulfillment envelope consistent with the other conditions.
